### PR TITLE
feat (mssql): #126, reuse the existing template

### PR DESCRIPTION
**Pull request by ivankudibal**
Add support for SQL Database in Azure (MSSQL powered)

Coordinated with xe-nvdk

### CODE REVIEW

**Comment by xe-nvdk** [comment]
I reviewed this template and I saw everything ok, except for the Windows CPU that is a metric not available in MSSQL in Azure. What do you think guys is the best approach? indicate in the readme that if the user is using MSSQL in Azure their needs to delete the pane of Windows CPU or "fork" the template and adapt to Azure? @mhall119 @ivankudibal what do you think?

**Comment by mhall119** [comment]
What would happen currently if you pointed it at MSSQL in Azure? Would the CPU metric just be blank in the dashboard? Or would there be some kind of error or failure when loading the dashboard?

**Comment by xe-nvdk** [comment]
> What would happen currently if you pointed it at MSSQL in Azure? Would the CPU metric just be blank in the dashboard? Or would there be some kind of error or failure when loading the dashboard?

Yes, the result would be "no results".

**Comment by mhall119** [comment]
In that case I think you could just put in the README that the CPU metrics won't work if you're pointing it at MSSQL in Azure.

You can also add a Note to a Dashboard cell, and have that note displayed when no data is available, mentioning this.

**Pull request merged**
