### PR TITLE
Docker Hub Template

### PR DESCRIPTION
**Pull request by xe-nvdk**

### CODE REVIEW

**Comment by russorat** [comment]
@xe-nvdk sorry for the delay here. do you think you can rebase from master which will make sure the CI passes?

**Comment by xe-nvdk** [comment]
Hi @russorat, I rebased, and the result is the same. Here is where the error is. I'm not sure that is in "my" template. 

image

**Comment by russorat** [comment]
i don't think your rebase worked. you still have an out of date workflow file: https://github.com/xe-nvdk/community-templates/blob/dockerhub/.github/workflows/main.yml

**Comment by xe-nvdk** [comment]
Hi @russorat do you mean to update my fork and

**Comment by xe-nvdk** [comment]
The branch dockerhub is giving me a hard time. I will update from master.

**Pull request closed without merging**
